name = "ImarisWriter"
uuid = "7685c673-c356-4b9b-8b22-c9f5550fdd46"
authors = ["Mark Kittisopikul <kittisopikulm@janelia.hhmi.org> and contributors"]
version = "0.2.0"

[deps]
ImarisWriter_jll = "9166e923-c553-51e5-a193-8d969705fd83"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
